<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <!-- Our theme includes -->
  <!-- Main components -->
  <INC file="$THEME_PATH$/decorations/decorations.inc"/>
	<INC file="$THEME_PATH$/toolbar/toolbar.inc" />
  <INC file="$THEME_PATH$/toolbar_buttons/buttons.inc" />
  
	<!-- Widgets -->
	<INC file="$THEME_PATH$/knobs/knobs.inc" />
	<INC file="$THEME_PATH$/sliders/sliders.inc" />
	<INC file="$THEME_PATH$/meters/meters.inc" />
	<INC file="$THEME_PATH$/settings_buttons/settings_buttons.inc" />
  <INC file="$THEME_PATH$/buttons/buttons.inc" />
  <INC file="$THEME_PATH$/switches/switches.inc" />
</DUMMY>